### ISSUE TITLE
Subfolder link giving wrong address when opening in browser with no trailing slash in the end

### ISSUE THREAD

**Issue by ghost** [mcnewton/nginx_webdav#1]
Hello,

When applying this config to my WebDAV server, I noticed that subfolder links are broken in the web browser. To be precise, let's say we have a WebDAV share at
`https://example.com/webdav/`
so, if there is a folder called 'folder1' when you are clicking it, it shall take you to
`https://example.com/webdav/folder1/`
and when you open a file in the folder, it will be
`https://example.com/webdav/folder1/sample.txt`
everything works fine at this moment.

However, when you open the share without a trailing slash in the end,
`https://example.com/webdav`
When you click on 'folder1', it will instead take you to 
`https://example.com/folder1`
and thus, you get a 404 error. If you open the folder as `https://example.com/webdav/folder1` without trailing slash and attempt to open the file in it, it will take you to
`https://example.com/webdav/sample.txt`
and you will also get a 404 error.

I have little knowledge of Nginx, so I don't know why it happened. For now, the temporary fix for me is to disable the part for working with Finder and Explorer and let the browser auto-redirect all links to the version with a trailing slash.

Best regards
Jayden

**Comment by mcnewton** [comment]
Thanks. It was mangling the URI for all requests, so the browser's GET got the same treatment as MOVE/DELETE from WebDav. This confused autoindex which expected a / on the end of the URI.

Patch seems to fix it for me (I've tested Windows and Linux, but not MacOS).
